### ISSUE TITLE
Netflix eureka client dependency

### ISSUE THREAD

**Issue by egnaf** [Reckue/account-api#27]
Hello!
Need to add the Netflix eureka client dependency.

1. Add this dependency.
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    <version>2.2.2.RELEASE</version>
</dependency>
```

2. Configure main class.
```java
@EnableEurekaClient
```

3. Rename the `application.yml` to `bootstrap.yaml`.

4. Configure `bootstrap.yml`. 
- Need to add the `eureka.client.serviceUrl.defaultZone` to only the `cloud` spring profile.
- Need to add the `spring.application.name` for all spring profiles.
```yaml
server:
  port: 8001

spring:
  application:
    name: post-api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
```

That's all. Many thanks.
